function tf = load_SIS(varargin)
% The function load_SIS(filepath) is designed
% to load the SIS h5 data file into the workspace.
% Input varargin{1} is a string that contain the full filename
% with its path

% return true if successfully loaded, otherwise return false.
tf=true;
if nargin~=1
%     errordlg('There should be only one input -- the data varargin{1}','Wrong argument No.');
    tf=false;
    return
end

[~, var_name, ext] = fileparts(varargin{1});
% if ~strcmpi(ext,'.h5')
%     %     errordlg(['The file "' varargin{1} '" is not a .nxs file!'],'Wrong file format');
%     tf=false;
%     return
% end

% check if it is from SIS
try
    sisinfo = h5info([var_name ext]);
    [sischeck,sischeck2] = sisinfo.Groups.Name; % need to check if the config of the file changes
    if ~strcmpi(sischeck,'/Electron Analyzer')
        %     errordlg(['The file "' varargin{1} '" is not a .nxs file!'],'Wrong file format');
        tf=false;
        return
    end
catch
    tf=false;
    return
end
%var_list=get(handles.listbox_Current_Folder,'String');
%var_index=get(handles.listbox_Current_Folder,'Value');

%for ii=1:length(var_index)
%var_name=var_list{var_index(ii)};
var_name = [var_name ext]; %combine the file name and extension
datav_new.value=h5read(var_name,'/Electron Analyzer/Image Data');
if ndims(datav_new.value)==3
    size3=size(datav_new.value);
    xnum=size3(1);ynum=size3(3);znum=size3(2);
    xaxis=h5readatt(var_name,'/Electron Analyzer/Image Data','Axis2.Scale');
    datav_new.x=xaxis(1):xaxis(2):xaxis(1)+(xnum-1)*xaxis(2);
    yaxis=h5readatt(var_name,'/Electron Analyzer/Image Data','Axis0.Scale');
    datav_new.z=yaxis(1):yaxis(2):yaxis(1)+(ynum-1)*yaxis(2);
    zaxis=h5readatt(var_name,'/Electron Analyzer/Image Data','Axis1.Scale');
    datav_new.y=zaxis(1):zaxis(2):zaxis(1)+(znum-1)*zaxis(2);
end

if ndims(datav_new.value)==2
    size3=size(datav_new.value);
    xnum=size3(1);ynum=size3(2);
    xaxis=h5readatt(var_name,'/Electron Analyzer/Image Data','Axis1.Scale');
    datav_new.x=xaxis(1):xaxis(2):xaxis(1)+(xnum-1)*xaxis(2);
    yaxis=h5readatt(var_name,'/Electron Analyzer/Image Data','Axis0.Scale');
    datav_new.y=yaxis(1):yaxis(2):yaxis(1)+(ynum-1)*yaxis(2);
end


%% Read in metadata

    for meta = {h5info(var_name ,'/Electron Analyzer/').Datasets.Attributes.Name}
        meta= meta(1);
        if strcmp(meta{1},'Acquisition Mode')
            datav_new.info.Aquisition_Mode= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
              'Acquisition Mode');
        end
        if strcmp(meta{1}, 'Intensity Units')
            datav_new.info.Intensity_Units= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Intensity Units');
        end
        if strcmp(meta{1}, 'Axis0.ScaleType')
            datav_new.info.Axis0.ScaleType= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis0.ScaleType');
        end
        if strcmp(meta{1}, 'Axis0.Scale')
            datav_new.info.Axis0.Scale= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis0.Scale');
        end
        if strcmp(meta{1}, 'Axis0.Description')
            datav_new.info.Axis0.Description= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis0.Description');
        end
        if strcmp(meta{1},'Axis0.Units')
            datav_new.info.Axis0.Units= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis0.Units');
        end
        if strcmp(meta{1},'Axis0.Mode')
            datav_new.info.Axis0.Mode= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis0.Mode');
        end
        if strcmp(meta{1}, 'Axis1.ScaleType')
            datav_new.info.Axis1.ScaleType= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis1.ScaleType');
        end
        if strcmp(meta{1}, 'Axis1.Scale')
            datav_new.info.Axis1.Scale= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis1.Scale');
        end
        if strcmp(meta{1}, 'Axis1.Description')
            datav_new.info.Axis1.Description= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis1.Description');
        end
        if strcmp(meta{1},'Axis1.Units')
            datav_new.info.Axis1.Units= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis1.Units');
        end
        if strcmp(meta{1},'Axis1.Mode')
            datav_new.info.Axis1.Mode= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Axis1.Mode');
        end
        if strcmp(meta{1},'Specified Number of Sweeps')
            datav_new.info.Sweeps= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Specified Number of Sweeps');
        end
        if strcmp(meta{1},'Dither Window (%)')
            datav_new.info.Dither.Window= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Dither Window (%)');
        end
        if strcmp(meta{1},'Dither Points')
            datav_new.info.Dither.Points= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Dither Points');
        end
        if strcmp(meta{1},'Lens Mode')
            datav_new.info.Lens_Mode= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Lens Mode');
        end
        if strcmp(meta{1},'Pass Energy (eV)')
            datav_new.info.EPass= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Pass Energy (eV)');
        end
        if strcmp(meta{1},'Energy Scale')
            datav_new.info.Energy_Scale= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Energy Scale');
        end
        if strcmp(meta{1},'Work Function (eV)')
            datav_new.info.Work_Function= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Work Function (eV)');
        end
        if strcmp(meta{1},'Dwell Time (ms)')
            datav_new.info.Dwell_Time= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Dwell Time (ms)');
        end
        if strcmp(meta{1},'Detector First X-Channel')
            datav_new.info.Detector_First_X_Channel= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Detector First X-Channel');
        end
        if strcmp(meta{1},'Detector Last X-Channel')
            datav_new.info.Detector_Last_X_Channel= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Detector Last X-Channel');
        end
        if strcmp(meta{1},'Detector First Y-Channel')
            datav_new.info.Detector_First_Y_Channel= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Detector First Y-Channel');
        end
        if strcmp(meta{1},'Detector Last Y-Channel')
            datav_new.info.Detector_Last_Y_Channel= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Detector Last Y-Channel');
        end
        if strcmp(meta{1},'Detector Slices')
            datav_new.info.Detector_Slices= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Detector Slices');
        end
        if strcmp(meta{1},'Detector ADC Mode')
            datav_new.info.Detector_ADC_Mode= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Detector ADC Mode');
        end
        if strcmp(meta{1},'Date Created')
            datav_new.info.Creation_Date= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Date Created');
        end
        if strcmp(meta{1},'Time Created')
            datav_new.info.Creation_Time= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Time Created');
        end
        if strcmp(meta{1},'Excitation Energy (eV)')
            datav_new.info.Excitation_Energy= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Excitation Energy (eV)');
        end
        if strcmp(meta{1},'Excitation Energy Read Device')
            datav_new.info.Excitation_Energy_Readback= ...
              h5readatt(var_name,'/Electron Analyzer/Image Data',...
               'Excitation Energy Read Device');
        end
    end
    for meta = {h5info(var_name ,'/').Attributes.Name}
        meta= meta(1);
        if strcmp(meta{1},'Comments')
            datav_new.info.Comments= ...
              h5readatt(var_name,'/',...
              'Comments');
        end
    end
        
if strcmpi(sischeck2,'/Other Instruments')
    try
        datav_new.info.ExitSlit=h5read(var_name,'/Other Instruments/Exit Slit');
%%%A complete version with a struct might be the following:
%         loc='/Other Instruments/Exit Slit';
%         datav_new.info.ExitSlit.value=h5read(var_name,loc);
%         datav_new.info.ExitSlit.Units= ...
%                       h5readatt(var_name,loc,...
%                       'Units');
%         datav_new.info.ExitSlit.Mode= ...
%                       h5readatt(var_name,loc,...
%                       'Mode');
%         datav_new.info.ExitSlit.Recording_Method= ...
%                       h5readatt(var_name,loc,...
%                       'Recording Method');
%         datav_new.info.ExitSlit.Record_Type= ...
%                       h5readatt(var_name,loc,...
%                       'Record Type');
    catch
    end
    try datav_new.info.ExitSlit=h5read(var_name,...
            '/Other Instruments/Exit Slit'); catch ;end 
    try datav_new.info.FE_Vert_Width=h5read(var_name,...
            '/Other Instruments/FE Vert. Width'); catch ;end 
    try datav_new.info.FE_Horiz_Width=h5read(var_name,...
            '/Other Instruments/FE Horiz. Width'); catch ;end 
    try datav_new.info.Phi=h5read(var_name,...
            '/Other Instruments/Phi'); catch ;end 
    try datav_new.info.Pressure_AC=h5read(var_name,...
            '/Other Instruments/Pressure AC (ACMI)'); catch ;end 
    try datav_new.info.Pressure_TC=h5read(var_name,...
            '/Other Instruments/Pressure TC (TCMP)'); catch ;end 
    try datav_new.info.Ring_Current=h5read(var_name,...
            '/Other Instruments/Storage Ring Current'); catch ;end 
    try datav_new.info.Temperature_Cryo=h5read(var_name,...
            '/Other Instruments/Temperature A (Cryostat)'); catch ;end 
    try datav_new.info.Temperature_Sample1=h5read(var_name,...
            '/Other Instruments/Temperature B (Sample 1)'); catch ;end 
    try datav_new.info.Temperature_Head=h5read(var_name,...
            '/Other Instruments/Temperature C (Head Mech)'); catch ;end 
    try datav_new.info.Temperature_Sample2=h5read(var_name,...
            '/Other Instruments/Temperature D (Sample 2)'); catch ;end 
    try datav_new.info.Temperature_Boot1=h5read(var_name,...
            '/Other Instruments/Temperature D2 (Boot 1)'); catch ;end 
    try datav_new.info.Temperature_Shield=h5read(var_name,...
            '/Other Instruments/Temperature D3 (Shield)'); catch ;end 
    try datav_new.info.Temperature_Boot2=h5read(var_name,...
            '/Other Instruments/Temperature D4 (Boot 2)'); catch ;end 
    try datav_new.info.Temperature_Cryopump=h5read(var_name,...
            '/Other Instruments/Temperature D5 (Cryopump)'); catch ;end 
    try datav_new.info.Theta=h5read(var_name,...
            '/Other Instruments/Theta'); catch ;end
    try datav_new.info.Tilt=h5read(var_name,...
            '/Other Instruments/Tilt'); catch ;end 
    try datav_new.info.X=h5read(var_name,...
            '/Other Instruments/X'); catch ;end 
    try datav_new.info.Y=h5read(var_name,...
            '/Other Instruments/Y'); catch ;end 
    try datav_new.info.Z=h5read(var_name,...
            '/Other Instruments/Z'); catch ;end 
    try datav_new.info.hv=h5read(var_name,...
            '/Other Instruments/hv'); catch ;end 
end        

    
%% 
assignin('base',strcat('SIS_',var_name(1:end-3)),datav_new);
vars=evalin('base','who');
%set(handles.listbox_Workspace,'String',vars);
%end

end
